name: cv
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.0.4
  firebase_core: ^2.1.1
  cubixd: 0.1.1
  get: 4.6.5
  google_fonts: 3.0.1
  flutter_markdown: 0.6.13
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

